server:
  port: 8090   # Tomcat service running on 8090

spring:
  application:
    name: blog-service

  datasource:
    url: jdbc:mysql://localhost:3307/blogsite?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: pass@word1
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update   # auto-create/update schema
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

logging:
  level:
    root: DEBUG
    org.springframework: DEBUG
    org.springframework.security: INFO
    org.hibernate.SQL: DEBUG       # shows SQL queries
    com.example: DEBUG             # your own package logs
  file:
    name: application.log          # optional: write logs to a file
